package com.example.zeroinbox

import android.content.Context
import android.content.SharedPreferences

/**
 * Manages IMAP credentials (email and App Password) locally in encrypted/private SharedPreferences.
 * Allows users to authenticate directly with Gmail IMAP without undergoing Google OAuth consent screens.
 */
class ImapAuthManager(context: Context) {

    companion object {
        private const val PREFS_NAME = "zero_inbox_imap_prefs"
        private const val KEY_IMAP_EMAIL = "imap_email"
        private const val KEY_IMAP_APP_PASSWORD = "imap_app_password"
        private const val KEY_IMAP_SERVER = "imap_server"
        private const val KEY_IMAP_PORT = "imap_port"

        const val DEFAULT_IMAP_SERVER = "imap.gmail.com"
        const val DEFAULT_IMAP_PORT = 993
    }

    private val prefs: SharedPreferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun isConfigured(): Boolean {
        val email = getEmail()
        val password = getAppPassword()
        return !email.isNullOrBlank() && !password.isNullOrBlank()
    }

    fun getEmail(): String? {
        val email = prefs.getString(KEY_IMAP_EMAIL, null)
        return if (!email.isNullOrBlank()) email.trim() else null
    }

    fun getAppPassword(): String? {
        val pwd = prefs.getString(KEY_IMAP_APP_PASSWORD, null)
        return if (!pwd.isNullOrBlank()) pwd.trim().replace(" ", "") else null
    }

    fun getServer(): String {
        return prefs.getString(KEY_IMAP_SERVER, null) ?: DEFAULT_IMAP_SERVER
    }

    fun getPort(): Int {
        return prefs.getInt(KEY_IMAP_PORT, DEFAULT_IMAP_PORT)
    }

    fun saveCredentials(email: String, appPassword: String, server: String = DEFAULT_IMAP_SERVER, port: Int = DEFAULT_IMAP_PORT) {
        prefs.edit()
            .putString(KEY_IMAP_EMAIL, email.trim())
            // App passwords generated by Google often have spaces like "abcd efgh ijkl mnop", remove spaces for auth
            .putString(KEY_IMAP_APP_PASSWORD, appPassword.trim().replace(" ", ""))
            .putString(KEY_IMAP_SERVER, server.trim().ifEmpty { DEFAULT_IMAP_SERVER })
            .putInt(KEY_IMAP_PORT, if (port > 0) port else DEFAULT_IMAP_PORT)
            .apply()
    }

    fun clearCredentials() {
        prefs.edit()
            .remove(KEY_IMAP_EMAIL)
            .remove(KEY_IMAP_APP_PASSWORD)
            .remove(KEY_IMAP_SERVER)
            .remove(KEY_IMAP_PORT)
            .apply()
    }
}
